import React from 'react'
import { Icon as _Icon, Text } from '../index'

const ICONS = [
  'redo',
  'redo-hover',
  'undo',
  'undo-hover',
  'book',
  'book-hover',
  'calendar-clock',
  'calendar-clock-hover',
  'people-add',
  'people-add-hover',
  'people',
  'people-hover',
  'flag',
  'flag-hover',
  'arrow-export-left',
  'arrow-export-left-hover',
  'arrow-export-right',
  'arrow-export-right-hover',
  'arrow-export-up',
  'arrow-export-up-hover',
  'beach',
  'beach-hover',
  'cube-tree',
  'cube-tree-hover',
  'list',
  'list-hover',
  'send',
  'send-hover',
  'arrow-reset',
  'arrow-reset-hover',
  'status',
  'status-hover',
  'document',
  'document-hover',
  'database',
  'database-hover',
  'arrow-download',
  'arrow-download-hover',
  'pos',
  'check-send',
  'check-send-hover',
  'spinner',
  'spinner-hover',
  'notebook-add',
  'notebook-add-hover',
  'expand-left',
  'expand-left-hover',
  'expand-right',
  'expand-right-hover',
  'open',
  'open-hover',
  'chevron-up-down',
  'chevron-up-down-hover',
  'dismiss-circle',
  'dismiss-circle-hover',
  'blocked',
  'blocked-hover',
  'briefcase',
  'briefcase-hover',
  'copy',
  'copy-hover',
  'terminate',
  'terminate-hover',
  'add-user',
  'add-user-hover',
  'user',
  'user-hover',
  'person-star',
  'person-star-hover',
  'login',
  'login-hover',
  'logout',
  'logout-hover',
  'select-all',
  'select-all-hover',
  'select-all-check',
  'select-all-check-hover',
  'percent',
  'dram',
  'attach',
  'attach-hover',
  'close',
  'close-hover',
  'add',
  'add-hover',
  'add-circle',
  'add-circle-hover',
  'phone',
  'phone-hover',
  'menu',
  'menu-hover',
  'repeat',
  'repeat-hover',
  'filter',
  'filter-hover',
  'trash',
  'trash-hover',
  'search',
  'search-hover',
  'eye-on',
  'eye-on-hover',
  'eye-off',
  'eye-off-hover',
  'mail',
  'mail-hover',
  'mail-add',
  'mail-add-hover',
  'mail-arrow-forward',
  'mail-arrow-forward-hover',
  'image',
  'image-hover',
  'link',
  'link-hover',
  'wallet',
  'wallet-hover',
  'minus',
  'minus-hover',
  'minus-circle',
  'minus-circle-hover',
  'more',
  'more-hover',
  'more-vertical',
  'more-vertical-hover',
  'warning',
  'warning-hover',
  'error',
  'error-hover',
  'favorite',
  'favorite-hover',
  'lock',
  'lock-hover',
  'unlock',
  'unlock-hover',
  'settings',
  'settings-hover',
  'comment',
  'comment-hover',
  'bookmark',
  'bookmark-hover',
  'notification',
  'notification-hover',
  'notification2',
  'notification2-hover',
  'savings',
  'savings-hover',
  'info',
  'info-hover',
  'question',
  'question-hover',
  'edit',
  'edit-hover',
  'share',
  'share-hover',
  'share2',
  'share2-hover',
  'home',
  'home-hover',
  'mark',
  'mark-hover',
  'checkmark',
  'checkmark-hover',
  'calendar',
  'calendar-hover',
  'calendar2',
  'calendar2-hover',
  'caret-left',
  'caret-left-hover',
  'caret-right',
  'caret-right-hover',
  'caret-down',
  'caret-down-hover',
  'caret-up',
  'caret-up-hover',
  'caret-down-right',
  'caret-down-right-hover',
  'arrow-left',
  'arrow-left-hover',
  'arrow-right',
  'arrow-right-hover',
  'arrow-up',
  'arrow-up-hover',
  'arrow-down',
  'arrow-down-hover',
  'arrow2-left',
  'arrow2-left-hover',
  'arrow2-right',
  'arrow2-right-hover',
  'arrow2-up',
  'arrow2-up-hover',
  'arrow2-down',
  'arrow2-down-hover',
  'arrow2-up-right',
  'arrow2-up-right-hover',
  'arrow2-up-left',
  'arrow2-up-left-hover',
  'arrow2-down-left',
  'arrow2-down-left-hover',
  'facebook',
  'twitter',
  'instagram',
  'linkedin',
  'apple',
  'medium',
  'telegram',
  'google',
  'youtube',
  'project-product',
  'only-employee',
  'units-employee'
]

export default {
  title: 'Icon',
  component: _Icon,
  argTypes: {
    type: {
      options: [
        'primary',
        'secondary',
        'tertiary',
        'disabled',
        'inverse',
        'selected',
        'brand',
        'danger',
        'warning',
        'success',
        'information',
        'discovery'
      ],
      control: { type: 'radio' }
    },
    size: {
      options: ['xxlarge', 'xlarge', 'large', 'medium', 'small', 'xsmall', 'xxsmall'],
      control: { type: 'radio' }
    }
  }
}

const Template = (args) => {
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'flex-start' }}>
      {/*{ICONS.length}*/}

      {ICONS.map((iconName) => (
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            padding: 10,
            flex: '70px',
            maxWidth: '70px'
          }}
          key={iconName}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              width: '40px',
              height: '40px',
              marginBottom: '5px',
              border: '1px solid #919191',
              backgroundColor: `${args.type == 'inverse' ? '#919191' : ''}`
            }}
          >
            <_Icon {...args} name={iconName} size={`${args.size}`} type={`${args.type}`} />
          </div>
          <Text size="small">{iconName}</Text>
        </div>
      ))}
    </div>
  )
}

export const Icon = Template.bind({})
Icon.args = {
  type: '',
  size: 'medium'
}
